name: ArisCommandWhitelist
version: 1.0
main: me.aris.ariswl.ArisWL
api-version: 1.20
folia-supported: true
author: VennLMAO
description: He thong chan lenh bao mat cho Aris Network.
commands:
  ariswl:
    description: Lenh quan tri plugin
    permission: ariswl.admin
    usage: /ariswl
permissions:
  ariswl.admin:
    default: op
  ariswl.bypass:
    default: op
